// @generated by tooling/scripts/update_time_locale_table.py
// Source: /Users/dolphilia/github/kestrel/docs/plans/bootstrap-roadmap/assets/time-format-locale-map.csv
// Generated: 2025-11-28T11:54:54Z

pub(crate) const TIME_LOCALE_TABLE: &[TimeLocaleEntry] = &[
    TimeLocaleEntry {
        id: "und",
        supports_rfc3339: true,
        supports_unix: true,
        supports_custom: true,
        status: LocaleStatus::Supported,
        fallback: None,
        notes: "Core.Time 既定ロケール。ICU 互換パターンは `tooling/scripts/update_time_locale_table.py` で生成されたテーブルが保証する。",
    },
    TimeLocaleEntry {
        id: "ja-JP",
        supports_rfc3339: true,
        supports_unix: true,
        supports_custom: true,
        status: LocaleStatus::Supported,
        fallback: Some("und"),
        notes: "Custom パターンは ICU 互換トランスレータ経由で `LocaleId::parse(\"ja-JP\")` と等価。フォールバックは und。",
    },
    TimeLocaleEntry {
        id: "tr-TR",
        supports_rfc3339: true,
        supports_unix: true,
        supports_custom: true,
        status: LocaleStatus::Supported,
        fallback: Some("und"),
        notes: "Core.Text でサポート済み。i/İ の特殊ケースも Custom フォーマット経由で利用可能。",
    },
    TimeLocaleEntry {
        id: "az-Latn",
        supports_rfc3339: true,
        supports_unix: true,
        supports_custom: false,
        status: LocaleStatus::Planned,
        fallback: Some("tr-TR"),
        notes: "Core.Text と同じく planned 扱い。LocaleId チェックは format()/parse() 手前で弾き、tr-TR へフォールバックを誘導。",
    },
    TimeLocaleEntry {
        id: "zh-TW",
        supports_rfc3339: true,
        supports_unix: true,
        supports_custom: false,
        status: LocaleStatus::Planned,
        fallback: Some("ja-JP"),
        notes: "幅変換マッピング確定後に Custom 対応を追加。現状は Rfc3339/Unix のみ許可し、文字幅は ja-JP を参照する。",
    },
];
