#ifndef REML_LEXER_TOKEN_H
#define REML_LEXER_TOKEN_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  REML_TOKEN_INVALID = 0,
  REML_TOKEN_EOF,
  REML_TOKEN_IDENT,
  REML_TOKEN_INT,
  REML_TOKEN_FLOAT,
  REML_TOKEN_STRING,
  REML_TOKEN_CHAR,
  REML_TOKEN_KW_RETURN,
  REML_TOKEN_KW_TRUE,
  REML_TOKEN_KW_FALSE,
  REML_TOKEN_KW_IF,
  REML_TOKEN_KW_ELSE,
  REML_TOKEN_KW_THEN,
  REML_TOKEN_KW_WHILE,
  REML_TOKEN_KW_WHEN,
  REML_TOKEN_KW_MATCH,
  REML_TOKEN_KW_WITH,
  REML_TOKEN_KW_LET,
  REML_TOKEN_KW_VAR,
  REML_TOKEN_KW_FN,
  REML_TOKEN_KW_PUB,
  REML_TOKEN_KW_USE,
  REML_TOKEN_KW_MODULE,
  REML_TOKEN_KW_TYPE,
  REML_TOKEN_LPAREN,
  REML_TOKEN_RPAREN,
  REML_TOKEN_LBRACE,
  REML_TOKEN_RBRACE,
  REML_TOKEN_LBRACKET,
  REML_TOKEN_RBRACKET,
  REML_TOKEN_COMMA,
  REML_TOKEN_SEMI,
  REML_TOKEN_COLON,
  REML_TOKEN_COLONEQ,
  REML_TOKEN_DOT,
  REML_TOKEN_DOTDOTEQ,
  REML_TOKEN_QUESTION,
  REML_TOKEN_ARROW,
  REML_TOKEN_EQ,
  REML_TOKEN_CARET,
  REML_TOKEN_LOGICAL_AND,
  REML_TOKEN_LOGICAL_OR,
  REML_TOKEN_PIPE,
  REML_TOKEN_PIPE_FORWARD,
  REML_TOKEN_PLUS,
  REML_TOKEN_MINUS,
  REML_TOKEN_STAR,
  REML_TOKEN_SLASH,
  REML_TOKEN_PERCENT,
  REML_TOKEN_DOTDOT,
  REML_TOKEN_EQEQ,
  REML_TOKEN_NOTEQ,
  REML_TOKEN_LT,
  REML_TOKEN_LE,
  REML_TOKEN_GT,
  REML_TOKEN_GE,
  REML_TOKEN_BANG
} reml_token_kind;

#ifdef __cplusplus
}
#endif

#endif
