name: OCaml dune test

on:
  push:
    paths:
      - 'compiler/ocaml/**'
      - '.github/workflows/ocaml-dune-test.yml'
      - 'docs/plans/bootstrap-roadmap/**'
  pull_request:
    paths:
      - 'compiler/ocaml/**'
      - '.github/workflows/ocaml-dune-test.yml'
      - 'docs/plans/bootstrap-roadmap/**'
  workflow_dispatch:

jobs:
  linux-dune-test:
    runs-on: ubuntu-latest
    name: Linux / dune test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Install LLVM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-18 llvm-18-dev llvm-18-tools
          # シンボリックリンク作成（llvm-as, opt, llc を使えるように）
          sudo ln -sf /usr/bin/llvm-as-18 /usr/bin/llvm-as
          sudo ln -sf /usr/bin/opt-18 /usr/bin/opt
          sudo ln -sf /usr/bin/llc-18 /usr/bin/llc
          # バージョン確認
          llvm-as --version
          opt --version
          llc --version

      - name: Install dependencies
        run: |
          opam install . --deps-only --with-test --yes
        working-directory: compiler/ocaml

      - name: dune test
        run: |
          opam exec -- dune test
        working-directory: compiler/ocaml

      - name: Upload LLVM IR artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: llvm-ir-artifacts
          path: |
            /tmp/reml_verify_*.ll
            /tmp/reml_verify_*.bc
          retention-days: 7
